import type { Metadata } from 'next'
import { Inter, Bungee_Spice, Poppins } from 'next/font/google'
import './globals.css'
import { ProvideTheme, ProvideNextUI } from './providers'

// const inter = Inter({ subsets: ['latin'] })

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'] 
})

export const bungeeSpice = Bungee_Spice({
  weight: ['400'],
  subsets: ['latin'], 
  variable: "--font-bungee-spice", 
  display: "swap"
}) 

export const metadata: Metadata = {
  title: 'Ajay Gaur - Full Stack Developer',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"  suppressHydrationWarning>
      <body className={`${poppins.className} ${bungeeSpice.variable} `}>
        <ProvideTheme>
          <ProvideNextUI>
            {children}
          </ProvideNextUI>
        </ProvideTheme>
      </body>
    </html>
  )
}
